# Generated by Django 2.0.2 on 2018-02-06 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('word_proc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng', models.CharField(max_length=32)),
                ('rus', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_tans', models.CharField(max_length=32)),
                ('rating', models.IntegerField()),
                ('last_drilled', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_proc.Dictionary')),
            ],
        ),
        migrations.RemoveField(
            model_name='words',
            name='user',
        ),
        migrations.DeleteModel(
            name='Words',
        ),
    ]
