# Generated by Django 2.0.2 on 2018-02-06 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word_proc', '0002_auto_20180206_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwords',
            old_name='user_tans',
            new_name='user_trans',
        ),
    ]
