# Generated by Django 2.0.2 on 2018-05-30 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word_proc', '0003_auto_20180206_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionary',
            name='id',
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='eng',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='drills',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userwords',
            name='last_drilled',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userwords',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
