# Generated by Django 2.0.2 on 2018-05-30 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word_proc', '0004_auto_20180530_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwords',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
