# Generated by Django 2.0.2 on 2018-06-01 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('word_proc', '0005_auto_20180530_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwords',
            name='last_rating_update',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userwords',
            name='learned',
            field=models.BooleanField(default=False),
        ),
    ]
