# Generated by Django 2.0.2 on 2018-06-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_proc', '0006_auto_20180601_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwords',
            name='success_run',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
