# Generated by Django 2.0.2 on 2018-06-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_proc', '0008_auto_20180604_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drills',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
